[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Underline"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window.dimensions]
columns = 133
lines = 40
